name: Latest blog post workflow
on:
  schedule: # RSS í”¼ë“œë¥¼ ë§¤ì¼ í™•ì¸
    - cron: "0 0 * * *"
  workflow_dispatch: # ìˆ˜ë™ ì‹¤í–‰ ê°€ëŠ¥

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://nullisdefined.site/feed.xml"
          max_post_count: 5
          template: |
            <table>
            <tr>
            <td align="center">
            ğŸ“
            </td>
            <td>
            <strong><a href="$url">$title</a></strong><br/>
            <sub>$date</sub>
            </td>
            </tr>
            </table>
          commit_message: "Updated with latest blog posts"
          committer_username: "blog-post-bot"
          committer_email: "blog-post-bot@example.com"
          gh_token: ${{ secrets.GH_TOKEN }}
          date_format: "MMM dd, yyyy"
